POST http://localhost:3500/v1.0/invoke/orderservice/method/order/create

{ "data": {"orderId":"42"} }

###

GET http://localhost:3500/v1.0/invoke/orderservice/method/order/get



DELETE http://localhost:3500/v1.0/invoke/orderservice/method/order/delete
